meta:
  pos_unit: "cm"
  rot_unit: "deg"

poses: # for aruco detect & pick & down offset positions
  "1":
    xyz_cm:    [-16.02, 31.85,  9.84]
    rpy_deg:   [ 5.89, -34.40, 41.57]
    offset_cm: [ 0.5,  -0.3,   0.0 ]
    z_lift_cm: 6.0
    note: "1번 상차"

  "2":
    xyz_cm:    [0.15, 24.83, 5.26]
    rpy_deg:   [0.0, -90, 0.0]
    offsets:
      "4": # 다리
        offset_cm: [3.0, -6.0, 8.0]
        z_lift_cm: 8.0
      "5": # 키트
        offset_cm: [0.0, 0.0, 0.0]
        z_lift_cm: 8.0
      "6": # 상판
        offset_cm: [-2.5, -2.0, 8.0]
        z_lift_cm: 8.0
      "7": # 바퀴
        offset_cm: [3.0, -4.0, 5.3]
        z_lift_cm: 6.0
    note: "2번 상차"

  "3":
    xyz_cm:    [-6.40, 11.09, 15.71]
    rpy_deg:   [ 2.32, -57.76, 51.43]
    offset_cm: [ 0.0,   0.0,   0.0 ]
    z_lift_cm: 8.0
    note: "3번 상차"

  "4":
    xyz_cm:    [11, 7,  16.5]
    rpy_deg:   [ 4.5, -66, -39]
    offset_cm: [ -0.5,  -0.5,   5.5 ]
    z_lift_cm: 3.0
    note: "다리 픽업(10시)"

  "5":
    xyz_cm:    [0.0, 0.0, 0.0]
    rpy_deg:   [0.0, 0.0, 0.0]
    offset_cm: [0.0, 0.0, 0.0]
    z_lift_cm: 5.0
    note: "키트 픽업"
  
  "6":
    xyz_cm:    [-6.40, 11.09, 15.71]
    rpy_deg:   [ 0, -57.76, 50.0]
    offset_cm: [ 4.0,   0.0,   4.5 ]
    z_lift_cm: 3.0
    note: "상판 픽업(8시)"

  "7":
    xyz_cm:    [-10, -6,  14.6]
    rpy_deg:   [ 7, -62, 145]
    offset_cm: [ 0.5,  -0.3,   0.0 ]
    z_lift_cm: 6.0
    note: "바퀴 픽업(4시)"

  "8":
    xyz_cm:    [4.8, 11.4, 32.6]
    rpy_deg:   [2, -3, 5]
    offset_cm: [0.0, 0.0, 0.0]
    z_lift_cm: 0.0
    note: "대기 위치"