name: picking_arm_bridge
topics:
  # --- [명령] 서버(59) -> 로봇(60) ---
  /robot1/order_command:
    from_domain: 59
    to_domain: 60
    remap: /order_command
    type: std_msgs/msg/Float64

  # --- [상태] 로봇(60) -> 서버(59) ---
  /robot_state:
    from_domain: 60
    to_domain: 59
    remap: /robot1/robot_state
    type: std_msgs/msg/Int8