name: packing_arm_bridge
topics:
  # --- [명령] 서버(59) -> 로봇(61) ---
  /robot2/order_command:
    from_domain: 59
    to_domain: 61
    remap: /order_command
    type: std_msgs/msg/Float64

  # --- [상태] 로봇(61) -> 서버(59) ---
  /robot_state:
    from_domain: 61
    to_domain: 59
    remap: /robot2/robot_state
    type: std_msgs/msg/Int8