name: lovo_robot_bridge

topics:
  # Domain 70 → 60 (PC → Robot1)###########################################
##########################################################################
  /robot1/PTP_gripper_command:
    type: std_msgs/msg/Int32
    from_domain: 70
    to_domain: 60
    remap: /PTP_gripper_command

  /robot2/PTP_gripper_command:
    type: std_msgs/msg/Int32
    from_domain: 70
    to_domain: 61
    remap: /PTP_gripper_command

  /robot1/PTP_servo_status:
      type: std_msgs/msg/Bool
      from_domain: 70
      to_domain: 60
      remap: /PTP_servo_status

  /robot2/PTP_servo_status:
      type: std_msgs/msg/Bool
      from_domain: 70
      to_domain: 61
      remap: /PTP_servo_status

  /joint_states:
    type: sensor_msgs/msg/JointState
    from_domain: 60
    to_domain: 70
    remap: /robot1/joint_states

  /joint_states:
    type: sensor_msgs/msg/JointState
    from_domain: 61
    to_domain: 70
    remap: /robot2/joint_states

  /PTP_tcp_pose:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 60
    to_domain: 70
    remap: /robot1/PTP_tcp_pose
  /PTP_tcp_pose:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 61
    to_domain: 70
    remap: /robot2/PTP_tcp_pose

  /robot1/PTP_goal_pose:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 70
    to_domain: 60
    remap: /PTP_goal_pose

  /robot2/PTP_goal_pose:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 70
    to_domain: 61
    remap: /PTP_goal_pose

  /robot1/order_command:
    type: std_msgs/msg/Float64
    from_domain: 70
    to_domain: 60
    remap: /order_command

  /robot2/order_command:
    type: std_msgs/msg/Float64
    from_domain: 70
    to_domain: 61
    remap: /order_command

  /robot1/PTP_capture_image_with_command/compressed:
    type: lovo_interfaces/msg/CaptureImageWithCommand
    from_domain: 70
    to_domain: 60
    remap: /PTP_capture_image_with_command/compressed
  /robot2/PTP_capture_image_with_command/compressed:
    type: lovo_interfaces/msg/CaptureImageWithCommand
    from_domain: 70
    to_domain: 61
    remap: /PTP_capture_image_with_command/compressed   


##########################################################################


###########################################################################
